### ISSUE TITLE
NLP课程作业文件

### ISSUE THREAD

**Issue by pengyou200902** [tsuirak/deeplearning.ai#3]
up主，请问你的NLP课程里有assignment和original这两个文件夹里面分别是什么文件呢？为什么assignment里那么多，original里那么少，还有用到的数据之类的都去哪里下载呢？

**Comment by tsuirak** [comment]
Assignment里面是作业的答案 而original是作业 但并没有答案 数据都在对应的assignment/week下面




| |
RoseXIN
|
|
rosexin13@yeah.net
|

Signature is customized by Netease Mail Master

在2020年07月13日 14:39，Friende 写道：

up主，你的NLP课程里有assignment和original这两个文件夹里面分别是什么文件呢？为什么assignment里那么多，original里那么少，还有用到的数据之类的都去哪里下载呢？

**Comment by pengyou200902** [comment]
> Assignment里面是作业的答案 而original是作业 但并没有答案 数据都在对应的assignment/week下面 | | RoseXIN | | rosexin13@yeah.net | Signature is customized by Netease Mail Master 在2020年07月13日 14:39，Friende 写道： up主，你的NLP课程里有assignment和original这两个文件夹里面分别是什么文件呢？为什么assignment里那么多，original里那么少，还有用到的数据之类的都去哪里下载呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢up主
