### ISSUE TITLE
Trax安装失败

### ISSUE THREAD

**Issue by chenjie97** [tsuirak/deeplearning.ai#4]
请问您是怎么安装trax的，我安装一直报错。可能是我的新环境没有TensorFlow和jax jaxlib
后来装jaxlib的时候一直报错，后来发现jaxlib是不是不支持windows 。
所以现在没办法安装trax，想请教一下您是怎么安装trax的

**Comment by tsuirak** [comment]
你好，我的电脑是mac 所以可能没有遇到和你一样的问题。只能您自己再多google一下了

**Comment by chenjie97** [comment]
谢谢您的回复！jaxlib jax并不支持WINDOWS，害我折腾好久，哈哈哈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tsuiraku"<notifications@github.com&gt;; 
发送时间: 2020年10月14日(星期三) 上午10:25
收件人: "tsuirak/deeplearning.ai"<deeplearning.ai@noreply.github.com&gt;; 
抄送: "陈杰"<1457245669@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tsuirak/deeplearning.ai] Trax安装失败 (#4)





 
你好，我的电脑是mac 所以可能没有遇到和你一样的问题。只能您自己再多google一下了
